### ISSUE TITLE
The probability of certain events should be 0

### ISSUE THREAD

**Issue by gowthamnatarajan** [amidst/toolbox#82]
During initialization the probability is set to random / uniform. The problem with this is that even though certain events can never occur and never occurs in the data, their probability is non-zero in the model. An option to set all probabilities should be set to 0 during initialization should be available.

**Comment by andresmasegosa** [comment]
Zero probabilities are quite hard in probabilistic modelling. If one state of a binary variable has zero probability, maybe the binary variable itself does not make sense, because there is no stochastic process we need to model. 

But, you can circumvent that by "editing" the learnt model and hard-coding the zero probs.

**Comment by gowthamnatarajan** [comment]
Ok, Thanks

**Comment by gowthamnatarajan** [comment]
After initializing the network, can I just make all the probabilities to be 0? And then use MLE to train the model?

**Comment by gowthamnatarajan** [comment]
I want to initialize all multinomial distributions to 0. Any easy way I can do that?

**Comment by andresmasegosa** [comment]
No, simply because a multinomial with all probabilities equal to zero is not a valid distribution. 

But you can use the method "setLaplace(false)" of the ParallelMaximumLikelihood class to deactivate the Laplace correction. So if one state is not observed, a zero probability will be assigned.

**Comment by gowthamnatarajan** [comment]
It worked. Thanks a lot :).
